# Generated by Django 2.1 on 2018-08-20 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kayitislemleri', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personel',
            name='position',
            field=models.CharField(default='deneme', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personel',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='personel',
            name='photo',
            field=models.CharField(default='default.jpg', max_length=25),
        ),
    ]
