# Generated by Django 2.1 on 2018-08-20 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kayitislemleri', '0002_auto_20180820_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personel',
            name='photo',
        ),
    ]
