# Generated by Django 2.1 on 2018-08-20 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kayitislemleri', '0003_remove_personel_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='personel',
            name='gender',
            field=models.CharField(default='Woman', max_length=5),
            preserve_default=False,
        ),
    ]
