# Generated by Django 2.1 on 2018-08-20 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kayitislemleri', '0004_personel_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='personel',
            name='facebook',
            field=models.CharField(default='twitter.com', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personel',
            name='twitter',
            field=models.CharField(default='facebook.com', max_length=50),
            preserve_default=False,
        ),
    ]
